dotnet5 changes
Epinova/Addon.Episerver.EnvironmentSynchronizer pull request #11
Opened 2022-05-04 07:10 UTC by Schlebbe

2022-05-05 06:50 UTC, LinusEkstrom approved these changes

2022-05-05 13:12 UTC, ovelartelius approved these changes

2022-06-20 13:20 UTC, vansterhant requested changes
The I read the code the DI-registrations are now doubled and for the EnvironmentSynchronizationManager registered both on the interface and the implementation?

[ServiceConfiguration(ServiceType = typeof(IEnvironmentSynchronizationManager))]

2022-06-20 13:20 UTC, vansterhant commented on README.md
> +		public void ConfigurationServices(IServiceCollection services)
Spelling mistake of the method It's called "ConfigureServices"

2022-06-20 13:20 UTC, vansterhant commented on Addon.Episerver.EnvironmentSynchronizer/Configuration/ServiceCollectionExtensions.cs
> +            services.AddSingleton<IConfigurationReader, ConfigurationReader>();
If the dependencies are added this way, one should drop the Serviceconfiguration-attributes, right? 
[ServiceConfiguration(typeof(IConfigurationReader))]

2023-02-25 16:02 UTC, merged